# Generated by Django 2.2.19 on 2022-09-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.SlugField(),
        ),
    ]
